# Generated by Django 5.0.2 on 2024-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.FileField(upload_to='f_test/', verbose_name='头像'),
        ),
    ]
