# Generated by Django 5.0.2 on 2024-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='file',
            field=models.FileField(default=111, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
