# Generated by Django 5.0.2 on 2024-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailValid',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telephone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='face_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
